### ISSUE TITLE
[META] build out minimum viable product feature set

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#4]
Log In / Sessions
- [x] Ability to share sessions across sites https://github.com/backdrop-ops/forum.backdropcms.org/issues/1

Node / Question features
- [x] Follow a conversation (Flag for "Follow")
- [x] Allow a tags field for users to enter whatever they want (field "Tags")

Comment / Answer features
- [x] Mark an answer as  `THE Accepted answer` (Flag)
- [x] Mark an answer as `Helpful` (Flag)
- [x] Mark an answer as `Spam or abusive` (Flag)

Pages for the forum:
- [x] Provide a list of all topics (View of all taxonomy terms) 
- [x] Provide a list of all posts in a topic (View of nodes with term)
- [x] Provide a threaded list of all comments on a post (View of comments on node)
- [x] Provide a list of all "followed" topics (View of all own "Followed" flagged items)

Search
- [x] Start with core search, iterate as necessary

User account features
- [x] All: add a post into a topic (create a node)
- [x]  All: add comments to a post (post a comment)
- [x] All: flag comments that are not your own (flag content / comments)
- [x] Forum moderator role: people empowered to promote topics (flag)
- [x] Forum moderator role: people empowered to change users roles

Review / Revise things as necessary
- [x] https://github.com/backdrop-ops/forum.backdropcms.org/issues/18 Flag language

**Comment by Graham-72** [comment]
Is our intended solution going to work like this?

1. Provide multiple named forums, set up by an administrator, and each being capable of being open to all or being a closed group that requires membership application.

2. Within a forum a user may initiate a topic, which may be a question or a piece of information for sharing and discussing. Initiating a topic would provide its first post.

3. Users may add a post (comment) to the topic and also add a response (comment) to a specific post.

4. Comments would be nested.

5. Comments may be voted as being answers, also marked by admin as answers, and perhaps should then appear at the top of the listing for that topic, rather than the normal date order.

6. We may need appointed moderators for each topic.

Considering all this do we think that the standard comment capability in Backdrop can meet our needs? Can a standard comment have extra data fields? Just asking.

**Comment by jenlampton** [comment]
Yes, exactly!  Well, almost exactly.

> each being capable of being open to all or being a closed group that requires membership application.

Each will be open to all.

> Considering all this do we think that the standard comment capability in Backdrop can meet our needs? Can a standard comment have extra data fields? Just asking.

A standard comment can have extra data fields, but that won't be necessary for any of the things in our MVP list. everything we need to accomplish can be done with flags + views.

**Comment by tomgrandy** [comment]
I'm sure there is a viable argument against this, but these features are important enough for using the forum and monitoring it to be included in the MVP:

- Votes on answers / Some kind of thumbs-up or facebook like type feature
- Ability to sort replies by # of votes
- Auto-unpublish after X reported flags
- Auto-block user ? if new and spamming, or X reported posts

**Comment by docwilmot** [comment]
What are the checked items in the first list?

**Comment by jenlampton** [comment]
> What are the checked items in the first list?

Those are things that are already built into forum.backdropcms.org.

> I'm sure there is a viable argument against this, but these features are important enough for using the forum and monitoring it to be included in the MVP.

In the meeting about priorities, we decided these items were not release blocking features. We decided that we would rather have a forum ASAP, than go a few more months without one. The reason they are in a second meta issue is because we also realized that they were important. Just not important enough that if we don't have them, we don't have a forum :)

> Votes on answers / Some kind of thumbs-up or facebook like type feature

This is sort-of already included in the feature `Mark an answer as Helpful` is in this list. And that one is already implemented, too!

> Ability to sort replies by # of votes

Please keep in mind that when we first launch there won't be any comments, or any votes, so there shouldn't be a need to sort them.

> Auto-unpublish after X reported flags
> Auto-block user ? if new and spamming, or X reported posts

Same goes for these two. When we launch there will not be any reported anythings.

**Comment by Dinornis** [comment]
>>What are the checked items in the first list?

>Those are things that are already built into forum.backdropcms.org @docwilmot

Would be nice to include the names of modules used for each feature.

**Comment by Dinornis** [comment]
I think the moderators and maybe even user will need to move posts between the different forums.  Not sure if you want to include that feature in this MVP list or in the second phase.

**Comment by docwilmot** [comment]
> Those are things that are already built into forum.backdropcms.org @docwilmot
> Would be nice to include the names of modules used for each feature.

In fact it would be nice to be a bit more clear about whats going on, actually. I feel a bit in the dark here. How exactly are we building things into? Are things being ported behind the scenes? Is there code somewhere we can see? And whats it being built into? The custom solution? Forum module?

**Comment by jenlampton** [comment]
There is no code. It's all just config!

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by Dinornis** [comment]
Awesome 8-)

**Comment by docwilmot** [comment]
Is there any way to actually test this out myself? Do I apply for a password or something?

**Comment by docwilmot** [comment]
Ignore me. I just logged in. 😄

**Comment by docwilmot** [comment]
And its looking good!! 
I do also get that AJAX 500 error as well.
And for the " Mark an answer as Helpful" flag: If I mark a thing as helpful, but change my mind, I might be thinking its just OK or chatter, not particularly helpful, but the link only offers for me to now mark it as "unhelpful" which is a bit negative. Furthermore, it might be an idea to allow to mark comments as unhelpful right away; there is no link for that though, you can only get to unhelpful by first marking helpful. Finally is the helpfulness the same as the Stackexchange ratings system, or will there be a separate up/down. like/dislike link coming?

**Comment by jenlampton** [comment]
> I do also get that AJAX 500 error as well.

Yes, I have filed an issue with flag module, we'll need to sort that out before launch :)

> And for the " Mark an answer as Helpful" flag: If I mark a thing as helpful, but change my mind, I might be thinking its just OK or chatter, not particularly helpful, but the link only offers for me to now mark it as "unhelpful" which is a bit negative. 

No, this is not the case. I specifically did not use the word "unhelpful" for precisely the reason you describe. The flag text is actually `I did not find this helpful` which is the opposite of `I found this helpful` and avoids calling the answer `unhelpful`, which I agree, is overly negative.

That said, we can certainly come up with better language for the flags! :)  This was just a first attempt based on previous conversations, but we should iterate :)

> Finally is the helpfulness the same as the Stackexchange ratings system, or will there be a separate up/down. like/dislike link coming?

I was thinking "helpful" would be our equivalent of Like or Thumbs-up.

**Comment by docwilmot** [comment]
> The flag text is actually I did not find this helpful which is the opposite of I found this helpful

True, reasonable.

> I was thinking "Helpful" would be our equivalent of Like or Thumbs-up.

I like it. 
Are we not going to allow negative ratings? As in a comment with a `100 people found this answer unhelpful`?

**Comment by jenlampton** [comment]
> Are we not going to allow negative ratings?

I was thinking maybe we'd add this later, once we have enough comments that we need to really be able to differentiate.

**Comment by tomgrandy** [comment]
> In the meeting about priorities, we decided these items were not release blocking features @tomgrandy. We decided that we would rather have a forum ASAP than go a few more months without one. The reason they are in a second meta issue is because we also realized that they were important -- just not important enough that if we don't have them, we don't have a forum :)

Understood.

**Comment by tomgrandy** [comment]
Forum (Module) returns this when trying to access a section or comment link:

> Backdrop Forum
Where all questions are answered with dignity and respect.
Error
The website encountered an unexpected error. Please try again later.

Flags throwing ajax error, but you already mentioned that.

Well, I wasn't much help.  

I like the layout of the custom forum better, but perhaps the forum module looks the same.  I just can't tell because of the above error.

**Comment by docwilmot** [comment]
> Yes, I have filed an issue with flag module, we'll need to sort that out before launch :)

Is there an error in watchdog or PHP that could help figure this out?

**Comment by docwilmot** [comment]
Any progress on this? What needs work?

**Comment by jenlampton** [comment]
I just pushed a version of bakery module up to all the *.backdropcms.org sites. It could use some testing!  :)  Thanks so much for the huge head start on that module @docwilmot :)

**Comment by jenlampton** [comment]
Since all the itmes in this meta are done, closing the issue. (We have separate issues for problems with individual items)
