### ISSUE TITLE
[META] build out other nice-to-have features

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#5]
## Nice to have:

Pages:
- [ ] FAQ page (featured or most common questions)
- [ ] Provide a list of all posts by a user on their profile page.

Node / Question features
- [ ] Promote as a FAQ 
- [ ] Email people when activity happens on the thread
- [ ] @mentions that send an email to said person
- [ ] Ability for people to bookmark a particular comment for later

Comment / Answer features
- [ ] Votes on answers / Some kind of thumbs-up or facebook like type feature
- [ ] Ability to sort replies by # of votes
- [ ] Auto-unpublish after X reported flags
- [ ] Auto-block user ? if new and spamming, or X reported posts

Search
- [ ] Do we need to search across multiple sites? (ack!)

User account features:
- [ ] Award points (or badges?) over time (+2 for answer, +1 for comment, +½ for reporting spam -1 for posting spam, tie in to auto block!)
- [ ] Allow users to subscribe / unsubscribe from email updates

**Comment by Dinornis** [comment]
I think soon or later you will find that there is a need to manage access to forums based on user roles, meaning only some roles having access to certain forums while other forums available to all.

**Comment by tomgrandy** [comment]
These are pretty important to the functionality of the Forum early on IMHO:

- Votes on answers / Some kind of thumbs-up or facebook like type feature
- Ability to sort replies by # of votes
- Auto-unpublish after X reported flags
- Auto-block user ? if new and spamming, or X reported posts

**Comment by docwilmot** [comment]
> Email people when activity happens on the thread

We dont have any contrib notifications type modules except Rules; will that do?

> @mentions that send an email to said person

Theres a [Mentions module ](https://www.drupal.org/project/mentions) (never heard of it till Google just now.)

> Ability for people to bookmark a particular comment for later

Dont quite understand what this means

> Votes on answers
 Ability to sort replies by # of votes
 Auto-unpublish after X reported flags
 Auto-block user ? if new and spamming, or X reported posts

Sounds like Flag + Rules

> Award points (or badges?) over time (+2 for answer, +1 for comment, +½ for reporting spam -1 for posting spam, tie in to auto block!)

Rules again?

> Allow users to subscribe / unsubscribe from email updates

Again Flag + Rules would do this

> Have some semi-private or access-controlled forums

I dont think we have any taxonomy access modules yet.

**Comment by jenlampton** [comment]
I bet we can do all this without rules ;)

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by docwilmot** [comment]
> I bet we can do all this without rules ;)

We can do anything. But we'd need to port some more, or custom code. 
Would like to hear your ideas though.

**Comment by Dinornis** [comment]
> Allow users to subscribe / unsubscribe from email updates
In my opinion this should be on the MVP list.

**Comment by jenlampton** [comment]
>  In my opinion  Allow users to subscribe / unsubscribe from email updates should be on the MVP list.

This one goes hand-in-hand with `Email people when activity happens on the thread`.  There's no point in subscribing to something if the site can't send an email. And we can't really start emailing people without a way for them to opt-out of those emails.

We know this is an important feature. The only reason we didn't have it on the MVP list is because it's very hard to do. We thought it would be better to start with follow, launch the site, then return to focus on the harder stuff.

**Comment by Dinornis** [comment]
In my experience, forums that do not provide this feature struggle with abandoned threads and lack of activity in general.
> This one goes hand-in-hand with Email people when activity happens on the thread. There's no point in subscribing to something if the site can't send an email. And we can't start emailing people without a way for them to opt-out of those emails.

Emails go out only to people who are subscribed and they can choose which threads they subscribe to.  The [Notifications module](https://www.drupal.org/project/notifications) should cover this.

Here is a [comparison list of related modules](https://groups.drupal.org/node/15928).

**Comment by jenlampton** [comment]
@Dinornis I've moved our conversation about emails over to the issue about emails (I just created it) so these thoughts won't be lost when we get around to working on it! :) https://github.com/backdrop-ops/forum.backdropcms.org/issues/10

**Comment by jenlampton** [comment]
I've created an issue for each of these items that is not yet done. Some of them have more info about the use  case (user story) and each has technical specs added too,.

Some of the details we talked about at the forum meeting(s), some stuff was added after being recommended by @docwilmot and @Dinornis and some stuff I just thought up now. 

Please everyone feel free to weigh in on each individual issue, if you like!

**Comment by docwilmot** [comment]
Maybe another nice-to-have which I really appreciate is a notification on a reply as to which comment or commenter it is replying to. Like http://gizmodo.com/this-goth-chicken-doesnt-conform-to-your-perfect-chicke-1791841530

**Comment by klonos** [comment]
There's a CKEditor plugin to support mentions: https://ckeditor.com/cke4/addon/mentions

We should consider that too, so that people can mention others in their comments.

**Comment by docwilmot** [comment]
I ported Mentions and CKEditor Mentions years ago
